"""
QuaC Pipeline to perform QC on bams and vcfs.
"""

WORKFLOW_PATH = Path(workflow.basedir).parent


configfile: config["workflow_config"]


##############   MODULES   ##############
include: "rules/common.smk"
include: "rules/relatedness_ancestry.smk"
include: "rules/fastq_qc.smk"
include: "rules/coverage_analysis.smk"
include: "rules/within_species_contamintation.smk"
include: "rules/vcf_stats.smk"
include: "rules/aggregate_results.smk"


#########################################


############   CONSTRAINTS   ############
wildcard_constraints:
    sample="|".join(SAMPLES),


#########################################


WGS_ONLY_COVERAGE_TARGETS = []
if not EXOME_MODE:
    WGS_ONLY_COVERAGE_TARGETS = [
        # indexcov
        OUT_DIR / PROJECT_LEVEL_QC_SUBDIR / "indexcov" / "index.html",
        # covviz
        OUT_DIR / PROJECT_LEVEL_QC_SUBDIR / "covviz" / "covviz_report.html",
    ]


rule all:
    input:
        ##### fastq #####
        [expand(str(OUT_DIR) + f"/{sample}/qc/fastqc-raw/{sample}-{{unit}}-{{reads}}_fastqc.html", unit=SAMPLES_CONFIG[sample]["fastq"].keys(), reads=["R1", "R2"]) for sample in SAMPLES_CONFIG],
        [expand(str(OUT_DIR) + f"/{sample}/qc/fastq_screen-raw/{sample}-{{unit}}-{{reads}}_screen.txt", unit=SAMPLES_CONFIG[sample]["fastq"].keys(), reads=["R1", "R2"]) for sample in SAMPLES_CONFIG],
        expand(str(OUT_DIR) + "/{sample}/qc/multiqc_initial_pass/multiqc_sample_rename_config/{sample}_rename_config.tsv",
                sample=SAMPLES),
        #### ancestry and relatedness #####
        # somalier
        OUT_DIR / PROJECT_LEVEL_QC_SUBDIR / "somalier" / "relatedness" / "somalier.html",
        OUT_DIR / PROJECT_LEVEL_QC_SUBDIR / "somalier" / "ancestry" / "somalier.somalier-ancestry.html",
        ##### coverage #####
        # samtools
        expand(OUT_DIR / "{sample}" / "qc" / "samtools-stats" / "{sample}.txt", sample=SAMPLES),
        # qualimap
        expand(OUT_DIR / "{sample}" / "qc" / "qualimap" / "{sample}" / "qualimapReport.html", sample=SAMPLES),
        # picard
        expand(
            OUT_DIR / "{sample}" / "qc" / "picard-stats" / "{sample}.{ext}",
            sample=SAMPLES,
            ext=[
                "alignment_summary_metrics",
                "quality_yield_metrics",
                "collect_wgs_metrics",
            ],
        ),
        # mosdepth
        expand(OUT_DIR / "{sample}" / "qc" / "mosdepth" / "{sample}.mosdepth.global.dist.txt", sample=SAMPLES),
        OUT_DIR / PROJECT_LEVEL_QC_SUBDIR / "mosdepth" / "mosdepth.html",
        # indexcov and covviz
        WGS_ONLY_COVERAGE_TARGETS,
        ##### cross-sample contamination #####
        # verifyBamID
        expand(OUT_DIR / "{sample}" / "qc" / "verifyBamID" / "{sample}.Ancestry", sample=SAMPLES),
        ##### VCF stats #####
        # bcftools
        expand(OUT_DIR / "{sample}" / "qc" / "bcftools-stats" / "{sample}.bcftools.stats", sample=SAMPLES),
        expand(OUT_DIR / "{sample}" / "qc" / "bcftools-index" / "{sample}.bcftools.index.tsv", sample=SAMPLES),
        ##### results aggregation #####
        expand(OUT_DIR / "{sample}" / "qc" / "multiqc_final_pass" / "{sample}_multiqc.html", sample=SAMPLES),
        OUT_DIR / PROJECT_LEVEL_QC_SUBDIR / "multiqc" / "multiqc_report.html",
