site_name: QuaC pipeline
nav:
  - Home: index.md
  - Miscellaneous:
      - ReadTheDocs- hosting docs: static_site.md

theme:
  name: readthedocs
  highlightjs: true

markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
