[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "QuaC pipeline"
authors = [{name = "test", email = "test@tester"}]
dynamic = ["version", "description"]
