qualimap:
  # TODO: verify the limits used
  avg_gc:
    human_readable: "% GC"
    min: 40.5
    max: 42.5

  percentage_aligned:
    human_readable: "% Aligned"
    min: 99
    max: 100

  mean_coverage:
    human_readable: "Mean coverage"
    min: 30
    max:

  median_coverage:
    human_readable: "Median coverage"
    min: 30
    max:

  mean_cov:median_cov:
    human_readable: "Mean-coverage:Media-coverage"
    min: 0.95
    max: 1.05

  median_insert_size:
    human_readable: "Median insert size"
    min: 250
    max:

picard:
  AlignmentSummaryMetrics:
    PCT_PF_READS_ALIGNED:
      min: 98
      max: 100

    PF_HQ_ALIGNED_Q20_BASES:
      min: 100000000000
      max:

    PCT_ADAPTER:
      min: 0
      max: 0.2

    PCT_CHIMERAS:
      min: 0
      max: 1

  QualityYieldMetrics:
    Q30_BASES:
      min: 80000000000
      max:
    perc_Q30_BASES:
      min: 85
      max:

  WgsMetrics:
    PCT_EXC_TOTAL:
      min: 0
      max: 15
    PCT_15X:
      min: 90
      max: 100

fastqc:
  - per_base_sequence_quality
  - per_tile_sequence_quality
  - per_sequence_quality_scores
  - per_base_sequence_content
  - per_sequence_gc_content
  - per_base_n_content
  - sequence_length_distribution
  - sequence_duplication_levels
  - overrepresented_sequences
  - adapter_content

fastq_screen:
  "Human percentage":
    min: 98.5
    max: 100
  "Mouse percentage":
    min: 8.1
    max: 11
  "Rat percentage":
    min: 9.0
    max: 11
  "Drosophila percentage":
    min: 1.1
    max: 1.8
  "Arabidopsis percentage":
    min: 0.8
    max: 1.2
  "No hits percentage":
    min: 0
    max: 1
  "others percentage":
    min: 0
    max: 1.0

verifybamid:
  FREEMIX:
    human_readable: "% Cross-sample contamination"
    min: 0
    max: 2

bcftools_stats:
  number_of_records:
    human_readable: "Total number of variants"
    min: 4900000
    max: 6100000

  number_of_SNPs:
    human_readable: "Total number of SNPs"
    min: 4000000
    max: 5000000

  number_of_indels:
    human_readable: "Total number of Indels"
    min: 820000
    max: 1150000

  perc_snps:
    human_readable: "%SNPs among all variants"
    min: 80
    max: 83

  perc_indels:
    human_readable: "%Indels among all variants"
    min: 17
    max: 20

  tstv:
    human_readable: "Transition to Transversion ratio"
    min: 1.92
    max: 1.95

  heterozygosity_ratio:
    human_readable: "Heterozygosity ratio = # het sites / # non-reference homozygous sites."
    min: 1.6
    max:

perc_variant_per_contig:
  chr1:
    min: 0.15
    max: 0.20
  chr2:
    min: 0.155
    max: 0.20
  chr3:
    min: 0.16
    max: 0.21
  chr4:
    min: 0.17
    max: 0.22
  chr5:
    min: 0.15
    max: 0.20
  chr6:
    min: 0.17
    max: 0.21
  chr7:
    min: 0.17
    max: 0.22
  chr8:
    min: 0.16
    max: 0.22
  chr9:
    min: 0.15
    max: 0.20
  chr10:
    min: 0.175
    max: 0.23
  chr11:
    min: 0.17
    max: 0.22
  chr12:
    min: 0.16
    max: 0.21
  chr13:
    min: 0.157
    max: 0.20
  chr14:
    min: 0.134
    max: 0.18
  chr15:
    min: 0.134
    max: 0.18
  chr16:
    min: 0.156
    max: 0.21
  chr17:
    min: 0.16
    max: 0.22
  chr18:
    min: 0.16
    max: 0.21
  chr19:
    min: 0.178
    max: 0.26
  chr20:
    min: 0.19
    max: 0.25
  chr21:
    min: 0.17
    max: 0.24
  chr22:
    min: 0.153
    max: 0.21
  chrX:
    min: 0.7
    max: 0.15
  chrY:
    min: 0.2
    max: 0.4
