qualimap:
  # TODO: verify the limits used
  avg_gc:
    human_readable: "% GC"
    min: 40.5
    max: 42.5

  percentage_aligned:
    human_readable: "% Aligned"
    min: 99
    max: 100

  mean_coverage:
    human_readable: "Mean coverage"
    min: 30
    max:

  median_coverage:
    human_readable: "Median coverage"
    min: 30
    max:

  mean_cov:median_cov:
    human_readable: "Mean-coverage:Media-coverage"
    min: 0.95
    max: 1.05

  median_insert_size:
    human_readable: "Median insert size"
    min: 250
    max:

fastqc:
  - per_base_sequence_quality
  - per_tile_sequence_quality
  - per_sequence_quality_scores
  - per_base_sequence_content
  - per_sequence_gc_content
  - per_base_n_content
  - sequence_length_distribution
  - sequence_duplication_levels
  - overrepresented_sequences
  - adapter_content

fastq_screen:
  "Human percentage":
    min: 98.5
    max: 100
  "Mouse percentage":
    min: 0
    max: 11
  "Rat percentage":
    min: 0
    max: 11
  "Drosophila percentage":
    min: 0
    max: 2
  "Arabidopsis percentage":
    min: 0
    max: 1.5
  "No hits percentage":
    min: 0
    max: 1
  "others percentage":
    min: 0
    max: 1.0
