qualimap:
  # TODO: verify the limits used
  avg_gc:
    human_readable: "% GC"
    min: 40.5
    max: 42.5

  percentage_aligned:
    human_readable: "% Aligned"
    min: 99
    max: 100

  mean_coverage:
    human_readable: "Mean coverage"
    min: 30
    max:

  median_coverage:
    human_readable: "Median coverage"
    min: 30
    max:

  mean_cov:median_cov:
    human_readable: "Mean-coverage:Media-coverage"
    min: 0.95
    max: 1.05

  median_insert_size:
    human_readable: "Median insert size"
    min: 250
    max:

picard:
  AlignmentSummaryMetrics:
    PCT_PF_READS_ALIGNED:
      min: 98
      max: 100

    PF_HQ_ALIGNED_Q20_BASES:
      min: 100000000000
      max:

    PCT_ADAPTER:
      min: 0
      max: 0.2

    PCT_CHIMERAS:
      min: 0
      max: 1

  QualityYieldMetrics:
    Q30_BASES:
      min: 80000000000
      max:
    perc_Q30_BASES:
      min: 85
      max:

fastqc:
  - per_base_sequence_quality
  - per_tile_sequence_quality
  - per_sequence_quality_scores
  - per_base_sequence_content
  - per_sequence_gc_content
  - per_base_n_content
  - sequence_length_distribution
  - sequence_duplication_levels
  - overrepresented_sequences
  - adapter_content

fastq_screen:
  "Human percentage":
    min: 98.5
    max: 100
  "Mouse percentage":
    min: 8.1
    max: 11
  "Rat percentage":
    min: 9.0
    max: 11
  "Drosophila percentage":
    min: 1.1
    max: 1.8
  "Arabidopsis percentage":
    min: 0.8
    max: 1.2
  "No hits percentage":
    min: 0
    max: 1
  "others percentage":
    min: 0
    max: 1.0

verifybamid:
  FREEMIX:
    human_readable: "% Cross-sample contamination"
    min: 0
    max: 2

bcftools_stats:
  number_of_records:
    human_readable: "Total number of variants"
    min: 4900000
    max: 6100000

  number_of_SNPs:
    human_readable: "Total number of SNPs"
    min: 4000000
    max: 5000000

  number_of_indels:
    human_readable: "Total number of Indels"
    min: 820000
    max: 1150000

  perc_snps:
    human_readable: "%SNPs among all variants"
    min: 80
    max: 83

  perc_indels:
    human_readable: "%Indels among all variants"
    min: 17
    max: 20

  tstv:
    human_readable: "Transition to Transversion ratio"
    min: 1.92
    max: 1.95

  heterozygosity_ratio:
    human_readable: "Heterozygosity ratio = # het sites / # non-reference homozygous sites."
    min: 1.6
    max:
