# general statistics table config
table_columns_visible:
    QualiMap:
        1_x_pc: False
        5_x_pc: False
        10_x_pc: False
        20_x_pc: False
        50_x_pc: False
        60_x_pc: False
        100_x_pc: False
        200_x_pc: False

    "Bcftools Stats":
        number_of_SNPs: False
        number_of_indels: False

    Samtools:
        non-primary_alignments: False
        reads_mapped: False
        reads_mapped_percent: False
        raw_total_sequences: False

    "FastQC (raw)": False

# order of modules to show in report
module_order:
    - cgds_qc_checkup
    - qualimap
    - picard
    - samtools
    - bcftools
    - fastqc:
          name: "FastQC (trimmed)"
          anchor: "trimmed"
          info: "This section of the report shows FastQC results after adapter trimming."
          target: ""
          path_filters:
              - "*/qc/fastqc-trimmed/*_fastqc.zip"
    - fastqc:
          name: "FastQC (raw)"
          anchor: "raw"
          path_filters:
              - "*/qc/fastqc-raw/*_fastqc.zip"
    - fastq_screen:
          name: "FastQ Screen (trimmed)"
          path_filters:
              - "*/qc/fastq_screen-trimmed/*"

# qualimap related
qualimap_config:
    general_stats_coverage:
        - 1
        - 5
        - 10
        - 15
        - 20
        - 30
        - 40
        - 50
        - 60
        - 100
        - 200

# configs for CGDS QC check-ups
# NOTE: This multiqc config file has hard-coded parameters, which is based on the QC-checkup config file.
# If parameters in QC-checkup config file get modified, this file may need to be edited correspondingly.
custom_data:
    qc_checkup_overall_summary:
        parent_id: "cgds_qc_checkup"
        parent_name: "CGDS - QC checkup"
        parent_description: "This section contains CGDS's QC checking results (Might not work well for WES)."
        id: "qc_checkup_overall_summary"
        section_name: "Overall QC checkup summary"
        description: "Overall QC checkup summary of results from several QC tools"
        file_format: "yaml"
        plot_type: "table"
        pconfig:
            table_title: "Overall QC checkup summary"

    qc_checkup_fastqc:
        parent_id: "cgds_qc_checkup"
        id: "qc_checkup_fastqc"
        section_name: "FastQC (trimmed)"
        description: 'Quick summary of FastQC (trimmed) results. See <a href="#trimmed">FastQC</a> section below for detailed results.'
        file_format: "yaml"
        plot_type: "table"
        pconfig:
            table_title: "FastQC - QC checkup"

    qc_checkup_fastq_screen:
        parent_id: "cgds_qc_checkup"
        id: "qc_checkup_fastq_screen"
        section_name: "FastQ Screen (trimmed)"
        description: 'Quick summary of FastQ Screen (trimmed) results. See <a href="#fastq_screen-1">FastQ Screen</a> section below for detailed results.'
        file_format: "yaml"
        plot_type: "table"
        pconfig:
            table_title: "FastQ Screen - QC checkup"
            only_defined_headers: False
            scale: "Blues"
        headers:
            "%Human":
                placement: 900
            "%Mouse":
                placement: 920
            "%Rat":
                placement: 940
            "%No hits":
                placement: 960
            "%Human_val":
                min: { { fastq_screen.human.min } }
                max: { { fastq_screen.human.max } }
                hidden: True
                placement: 910
            "%Mouse_val":
                min: { { fastq_screen.mouse.min } }
                max: { { fastq_screen.mouse.max } }
                hidden: True
                placement: 930
            "%Rat_val":
                min: 0
                max: { { fastq_screen.rat.min } }
                hidden: { { fastq_screen.rat.max } }
                placement: 950
            "%Drosophila_val":
                min: { { fastq_screen.drosophila.min } }
                max: { { fastq_screen.drosophila.max } }
                hidden: True
            "%Arabidopsis_val":
                min: { { fastq_screen.arabidopsis.min } }
                max: { { fastq_screen.arabidopsis.max } }
                hidden: True
            "%No hits_val":
                min: { { fastq_screen.nohits.min } }
                max: { { fastq_screen.nohits.max } }
                hidden: True
                placement: 970
            "%Adapters_val":
                min: { { fastq_screen.others.min } }
                max: { { fastq_screen.others.max } }
                hidden: True
            "%Ecoli_val":
                min: { { fastq_screen.others.min } }
                max: { { fastq_screen.others.max } }
                hidden: True
            "%Lambda_val":
                min: { { fastq_screen.others.min } }
                max: { { fastq_screen.others.max } }
                hidden: True
            "%MT_val":
                min: { { fastq_screen.others.min } }
                max: { { fastq_screen.others.max } }
                hidden: True
            "%PhiX_val":
                min: { { fastq_screen.others.min } }
                max: { { fastq_screen.others.max } }
                hidden: True
            "%Vectors_val":
                min: { { fastq_screen.others.min } }
                max: { { fastq_screen.others.max } }
                hidden: True
            "%Worm_val":
                min: { { fastq_screen.others.min } }
                max: { { fastq_screen.others.max } }
                hidden: True
            "%Yeast_val":
                min: { { fastq_screen.others.min } }
                max: { { fastq_screen.others.max } }
                hidden: True
            "%rRNA_val":
                min: { { fastq_screen.others.min } }
                max: { { fastq_screen.others.max } }
                hidden: True

    qc_checkup_qualimap_overall:
        parent_id: "cgds_qc_checkup"
        id: "qc_checkup_qualimap_overall"
        section_name: "Qualimap - Overall stats"
        description: 'Quick summary of Qualimap results. See <a href="#qualimap">QualiMap</a> section below for detailed results.'
        file_format: "yaml"
        plot_type: "table"
        pconfig:
            table_title: "Qualimap - Overall stats - QC checkup"
            only_defined_headers: False
            scale: "Blues"
        headers:
            avg_gc_val:
                min: { { qualimap.avg_gc.min } }
                max: { { qualimap.avg_gc.max } }
                hidden: True
            # if you change coverage limits, also change values in "qc_checkup_qualimap_chromosome_stats"
            mean_coverage_val:
                min: { { qualimap.mean_coverage.min } }
                hidden: True
            median_coverage_val:
                min: { { qualimap.median_coverage.min } }
                hidden: True
            percentage_aligned_val:
                min: { { qualimap.percentage_aligned.min } }
                max: { { qualimap.percentage_aligned.max } }
                hidden: True

    qc_checkup_qualimap_chromosome_stats:
        parent_id: "cgds_qc_checkup"
        id: "qc_checkup_qualimap_chromosome_stats"
        section_name: "Qualimap - Chromosome stats"
        description: 'Quick summary chromosome-level coverage info using Qualimap results. See <a href="#qualimap">QualiMap</a> section below for detailed results.'
        file_format: "yaml"
        plot_type: "linegraph"
        pconfig:
            id: qc_checkup_qualimap_chromosome_stats
            ymin: 0
            ymax: 100
            categories: True
            ylab: "Coverage (X)"
            extra_series:
                name: "Minimum required"
                data: [[0, { { qualimap.mean_coverage.min } }], [21, { { qualimap.mean_coverage.min } }], [22, { { qualimap.mean_coverage.min } }/2], [23, { { qualimap.mean_coverage.min } }/2]]
                dashStyle: "Dash"
                showInLegend: False
                color: "PaleVioletRed"

# define file pattern for custom configs
sp:
    qc_checkup_overall_summary:
        fn: "qc_checkup_overall_summary.yaml"
    qc_checkup_fastqc:
        fn: "qc_checkup_fastqc.yaml"
    qc_checkup_fastq_screen:
        fn: "qc_checkup_fastq_screen.yaml"
    qc_checkup_qualimap_overall:
        fn: "qc_checkup_qualimap_overall.yaml"
    qc_checkup_qualimap_chromosome_stats:
        fn: "qc_checkup_qualimap_chromosome_stats.yaml"
