channels:
  - conda-forge
  - bioconda
dependencies:
  - bcftools =1.12
  # other dependencies
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - c-ares=1.17.2
  - ca-certificates=2021.5.30
  - gsl=2.6
  - htslib=1.12
  - krb5=1.19.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.78.0
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libgcc-ng=11.1.0
  - libgfortran-ng=11.1.0
  - libgfortran5=11.1.0
  - libgomp=11.1.0
  - libnghttp2=1.43.0
  - libopenblas=0.3.17
  - libssh2=1.9.0
  - libstdcxx-ng=11.1.0
  - ncurses=6.2
  - openssl=1.1.1k
  - perl=5.32.1
  - tk=8.6.10
  - xz=5.2.5
