name: quac_common

channels:
  - conda-forge
  - bioconda

dependencies:
  - python==3.7.6
  - pandas==1.2.2
  - numpy==1.19.5
  - xlrd==1.2.0
  - ped_parser==1.6.6
  - fire==0.3.1
  - colorlog==4.7.2
  - black==20.8b1
