name: covviz

channels:
  - conda-forge

dependencies:
  - python==3.6.12
  - pip
  - pip:
      - covviz==1.3.0
      # - "--editable=git+git://github.com/brwnj/covviz.git@a1ea4d4c64d47e36c94500914182496f8edd2391"
