name: mosdepth

channels:
  - conda-forge
  - bioconda

dependencies:
  - mosdepth==0.3.1
  # other dependencies
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - c-ares=1.17.2
  - ca-certificates=2021.5.30
  - htslib=1.12
  - krb5=1.19.2
  - libcurl=7.78.0
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libgcc-ng=11.1.0
  - libgomp=11.1.0
  - libnghttp2=1.43.0
  - libssh2=1.9.0
  - libstdcxx-ng=11.1.0
  - ncurses=6.2
  - openssl=1.1.1k
  - pcre=8.45
  - tk=8.6.10
  - xz=5.2.5
