name: quac

channels:
  - conda-forge
  - bioconda

dependencies:
  - python==3.6.13
  - black==20.8b1
  - pylint==2.7.2
  - bioconda::snakefmt==0.4.0
  - bioconda::snakemake-minimal==6.0.5
  - pip==21.0.1
  - pip:
      - slurmpy==0.0.8
