channels:
  - conda-forge
  - bioconda
dependencies:
  - qualimap ==2.2.2d
  # other dependencies
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - alsa-lib=1.2.3
  - binutils_impl_linux-64=2.36.1
  - binutils_linux-64=2.36
  - bioconductor-biobase=2.52.0
  - bioconductor-biocgenerics=0.38.0
  - bioconductor-biocio=1.2.0
  - bioconductor-biocparallel=1.26.0
  - bioconductor-biostrings=2.60.0
  - bioconductor-delayedarray=0.18.0
  - bioconductor-genomeinfodb=1.28.0
  - bioconductor-genomeinfodbdata=1.2.6
  - bioconductor-genomicalignments=1.28.0
  - bioconductor-genomicranges=1.44.0
  - bioconductor-iranges=2.26.0
  - bioconductor-matrixgenerics=1.4.0
  - bioconductor-noiseq=2.36.0
  - bioconductor-rhtslib=1.24.0
  - bioconductor-rsamtools=2.8.0
  - bioconductor-rtracklayer=1.52.0
  - bioconductor-s4vectors=0.30.0
  - bioconductor-summarizedexperiment=1.22.0
  - bioconductor-xvector=0.32.0
  - bioconductor-zlibbioc=1.38.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.17.2
  - ca-certificates=2021.5.30
  - cairo=1.16.0
  - curl=7.78.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - fribidi=1.0.10
  - gcc_impl_linux-64=9.4.0
  - gcc_linux-64=9.4.0
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=9.4.0
  - gfortran_linux-64=9.4.0
  - giflib=5.2.1
  - graphite2=1.3.13
  - gsl=2.6
  - gxx_impl_linux-64=9.4.0
  - gxx_linux-64=9.4.0
  - harfbuzz=2.8.2
  - icu=68.1
  - jbig=2.1
  - jpeg=9d
  - kernel-headers_linux-64=2.6.32
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.78.0
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-devel_linux-64=9.4.0
  - libgcc-ng=11.1.0
  - libgfortran-ng=11.1.0
  - libgfortran5=11.1.0
  - libglib=2.68.3
  - libgomp=11.1.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libnghttp2=1.43.0
  - libopenblas=0.3.17
  - libpng=1.6.37
  - libsanitizer=9.4.0
  - libssh2=1.9.0
  - libstdcxx-devel_linux-64=9.4.0
  - libstdcxx-ng=11.1.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - make=4.3
  - ncurses=6.2
  - openjdk=11.0.9.1
  - openssl=1.1.1k
  - pango=1.48.7
  - pcre=8.45
  - pcre2=10.37
  - pixman=0.40.0
  - pthread-stubs=0.4
  - r-base=4.1.1
  - r-bh=1.75.0_0
  - r-bitops=1.0_7
  - r-crayon=1.4.1
  - r-formatr=1.11
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-getopt=1.20.3
  - r-lambda.r=1.2.4
  - r-lattice=0.20_44
  - r-matrix=1.3_4
  - r-matrixstats=0.60.0
  - r-optparse=1.6.6
  - r-rcurl=1.98_1.3
  - r-restfulr=0.0.13
  - r-rjson=0.2.20
  - r-snow=0.4_3
  - r-xml=3.99_0.6
  - r-yaml=2.2.1
  - readline=8.1
  - sed=4.8
  - sysroot_linux-64=2.12
  - tk=8.6.10
  - tktable=2.10
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-libxtst=1.2.3
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
