name: system_testing
on: [push, pull_request, workflow_dispatch]

jobs:
  create-env:
    name: ubuntu-20.04
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}
        
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        
      - name: Create quac environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge,bioconda,defaults
          auto-activate-base: false
          activate-environment: quac
          environment-file: configs/env/quac.yaml
      
      - name: Check conda solution
        run: |
          mamba env export
      
      - name: Check snakemake exists in conda env
        run: |
          which snakemake
          snakemake --version

      - uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3
      - name: Check singularity is working
        run: |
          singularity  --version

      - name: Set up dependencies for QuaC
        run: |
          bash src/setup_dependency_datasets.sh
      
      - name: Run QuaC system testing
        run: |
          python src/run_quac.py \
                --project_name test_project \
                --projects_path ".test/ngs-data/" \
                --pedigree ".test/configs/no_priorQC/project_2samples.ped" \
                --outdir "data/quac/results/test_project_2samples_wgs-no_priorQC/analysis" \
                --quac_watch_config "configs/quac_watch/wgs_quac_watch_config.yaml" \
                --workflow_config "configs/workflow.yaml"