name: system_testing
on:
  push:
    paths:
      - 'configs/env/quac.yaml'
      - '.github/workflows/system_testing.yml'


jobs:
  create-env:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
        
    # strategy:
    #   fail-fast: false

    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        
      - name: create environment with mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge,bioconda,defaults
          auto-activate-base: false
          activate-environment: quac
          environment-file: configs/env/quac.yaml
      
      - name: check solution
        run: |
          mamba env export
      
      - name: test snakemake
        run: |
          which snakemake
          snakemake --version

      - uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3
      - name: Run a singularity container
        run: |
          # singularity run docker://alpine cat /etc/os-release
          singularity  --version

      - name: Set up dependecies for QuaC
        run: |
          bash src/setup_dependency_datasets.sh
      
      - name: Run QuaC system testing
        run: |
          which python
          ls
          python src/run_quac.py \
                --project_name test_project \
                --projects_path ".test/ngs-data/" \
                --pedigree ".test/configs/no_priorQC/project_2samples.ped" \
                --outdir "data/quac/results/test_project_2samples_wgs-no_priorQC/analysis" \
                --quac_watch_config "configs/quac_watch/wgs_quac_watch_config.yaml" \
                --workflow_config "configs/workflow.yaml"